sdg_small = list(
  sdg1=c("no poverty", "end poverty", "poverty"),
  sdg2=c("end hunger", "hunger", "food security", "improved nutrition", "sustainable agriculture"),
  sdg3=c("good health", "well-being", "healthy lives"),
  sdg4=c("quality education", "inclusive education", "lifelong learning"),
  sdg5=c("gender equality", "empower women and girls"),
  sdg6=c("water and sanitation", "clean water", "sanitation"),
  sdg7=c("sustainable energy", "affordable energy", "clean energy", "reliable energy"),
  sdg8=c("sustainable economic growth", "decent work", "inclusive growth", "economic growth"),
  sdg9=c("resilient infrastructure","inclusive industrialization", "sustaianble industrialization", "innovation"),
  sdg10=c("reduced inequalities"),
  sdg11=c("sustainable cities"),
  sdg12=c("sustainable consumption", "responsible consumption", "sustainable production"),
  sdg13=c("climate action", "climate change", "climate change impact", "greenhouse gas", "ghg", "climate change"),
  sdg15=c("life below water"),
  sdg16=c("life on land", "biodiversity loss", "resilient ecosystems", "land degradation","desertification"),
  sdg17=c("peace", "justice", "strong institutions"))

dict = dictionary(sdg_small)
